name: agility_timer
description: 体育敏捷性反应训练计时器 - 节奏节拍器与随机变向信号训练工具
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
